--REBECCA LUDWIG

--List the names of pilots who have flown the most miles.
SELECT EMP_NUM, EMP_LNAME, EMP_FNAME, SUM(CHAR_DISTANCE) AS MILES_FLOWN
FROM TRIP_DIM INNER JOIN CHARTER_FACTS
ON TRIP_DIM.TRIP_ID = CHARTER_FACTS.TRIP_ID INNER JOIN PILOT_DIM
ON CHARTER_FACTS.PILOT_ID = PILOT_DIM.PILOT_ID
GROUP BY EMP_NUM, EMP_LNAME, EMP_FNAME, CHAR_DISTANCE
HAVING SUM(CHAR_DISTANCE) = 
	(
	SELECT TOP 1 SUM(CHAR_DISTANCE)
	FROM TRIP_DIM INNER JOIN CHARTER_FACTS
	ON TRIP_DIM.TRIP_ID = CHARTER_FACTS.TRIP_ID INNER JOIN PILOT_DIM
	ON CHARTER_FACTS.PILOT_ID = PILOT_DIM.PILOT_ID
	GROUP BY EMP_NUM, EMP_LNAME, EMP_FNAME, CHAR_DISTANCE
	)

--List the revenue by model and month in ascending order.
SELECT MOD_NAME, CHAR_MONTH, REVENUE
FROM PLANE_DIM INNER JOIN CHARTER_FACTS
ON PLANE_DIM.PLANE_ID = CHARTER_FACTS.PLANE_ID INNER JOIN TIME_DIM
ON CHARTER_FACTS.TIME_ID = TIME_DIM.TIME_ID
GROUP BY MOD_NAME, CHAR_MONTH, REVENUE
ORDER BY MOD_NAME ASC