--REBECCA LUDWIG

DROP TABLE CHARTER_FACTS
DROP TABLE TRIP_DIM
DROP TABLE TIME_DIM
DROP TABLE PLANE_DIM
DROP TABLE PILOT_DIM

--CREATE PILOT_DIM TABLE
CREATE TABLE PILOT_DIM
(
	PILOT_ID INT IDENTITY NOT NULL,
	EMP_NUM INT,
	EMP_LNAME NVARCHAR(15),
	EMP_FNAME NVARCHAR(15)
);

--CREATE PLANE_DIM TABLE
CREATE TABLE PLANE_DIM
(
	PLANE_ID INT IDENTITY NOT NULL,
	AC_NUMBER NVARCHAR(5),
	MOD_NAME NVARCHAR(20),
	MOD_CHG_MILE REAL
);

--CREATE TIME_DIM TABLE
CREATE TABLE TIME_DIM
(
	TIME_ID INT IDENTITY NOT NULL,
	CHAR_DATE DATE,
	CHAR_DAY INT,
	CHAR_MONTH INT,
	CHAR_YEAR INT
);

--CREATE TRIP_DIM TABLE
CREATE TABLE TRIP_DIM
(
	TRIP_ID INT IDENTITY NOT NULL,
	CHAR_TRIP INT,
	CHAR_DISTANCE REAL,
	CHAR_HOURS_FLOWN FLOAT,
	CHAR_FUEL_GALLONS FLOAT
);

--CREATE CHARTER_FACTS TABLE
CREATE TABLE CHARTER_FACTS
(
	FACT_ID INT IDENTITY NOT NULL,
	PILOT_ID INT,
	PLANE_ID INT,
	TIME_ID INT,
	TRIP_ID INT,
	REVENUE MONEY
) 

--DEFINE PILOT_DIM PK
ALTER TABLE PILOT_DIM
ADD CONSTRAINT PK_PILOT_DIM PRIMARY KEY (PILOT_ID)

--DEFINE PLANE_DIM PK
ALTER TABLE PLANE_DIM
ADD CONSTRAINT PK_PLANE_DIM PRIMARY KEY (PLANE_ID)

--DEFINE TIME_DIM PK
ALTER TABLE TIME_DIM
ADD CONSTRAINT PK_TIME_DIM PRIMARY KEY (TIME_ID)

--DEFINE TRIP_DIM PK
ALTER TABLE TRIP_DIM
ADD CONSTRAINT PK_TRIP_DIM PRIMARY KEY (TRIP_ID)

--DEFINE CHARTER_FACTS PKS & FKS
ALTER TABLE CHARTER_FACTS
ADD CONSTRAINT PK_CHARTER_FACTS PRIMARY KEY (FACT_ID),
	CONSTRAINT FK_CHARTER_FACTS_PILOT FOREIGN KEY (PILOT_ID) REFERENCES PILOT_DIM,
	CONSTRAINT FK_CHARTER_FACTS_PLANE FOREIGN KEY (PLANE_ID) REFERENCES PLANE_DIM,
	CONSTRAINT FK_CHARTER_FACTS_TIME FOREIGN KEY (TIME_ID) REFERENCES TIME_DIM,
	CONSTRAINT FK_CHARTER_FACTS_TRIP FOREIGN KEY (TRIP_ID) REFERENCES TRIP_DIM