--REBECCA LUDWIG

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE A10P3
AS
BEGIN

--POPULATE PILOT_DIM TABLE
INSERT INTO PILOT_DIM
SELECT EMP_NUM, EMP_LNAME, EMP_FNAME
FROM EMPLOYEE
WHERE EMP_NUM NOT IN (SELECT EMP_NUM FROM PILOT_DIM)
GROUP BY EMP_NUM, EMP_LNAME, EMP_FNAME

--POPULATE PLANE_DIM TABLE
INSERT INTO PLANE_DIM
SELECT AC_NUMBER, MOD_NAME, MOD_CHG_MILE
FROM AIRCRAFT, MODEL
WHERE AC_NUMBER NOT IN (SELECT AC_NUMBER FROM PLANE_DIM)
GROUP BY AC_NUMBER, MOD_NAME, MOD_CHG_MILE

--POPULATE TIME_DIM TABLE
INSERT INTO TIME_DIM
SELECT CHAR_DATE, CHAR_DAY = DAY(CHAR_DATE), CHAR_MONTH = MONTH(CHAR_DATE), CHAR_YEAR = YEAR(CHAR_DATE)
FROM CHARTER
WHERE CHAR_DATE NOT IN (SELECT CHAR_DATE FROM TIME_DIM)
GROUP BY CHAR_DATE

--POPULATE TRIP_DIM TABLE
INSERT INTO TRIP_DIM
SELECT CHAR_TRIP, CHAR_DISTANCE, CHAR_HOURS_FLOWN, CHAR_FUEL_GALLONS 
FROM CHARTER
WHERE CHAR_TRIP NOT IN (SELECT CHAR_TRIP FROM TRIP_DIM)

--POPULATE CHARTER_FACTS TABLE
INSERT INTO CHARTER_FACTS
SELECT PILOT_ID, PLANE_ID, TIME_ID, TRIP_ID, REVENUE = CHAR_FUEL_GALLONS * MOD_CHG_MILE
FROM PILOT_DIM, PLANE_DIM, TIME_DIM, TRIP_DIM
WHERE PILOT_ID NOT IN (SELECT PILOT_ID FROM CHARTER_FACTS)
GROUP BY PILOT_ID, PLANE_ID, TIME_ID, TRIP_ID, CHAR_FUEL_GALLONS, MOD_CHG_MILE

END
GO
